// atomic/templates/calendar/event-block/index.tsx
'use client'

import React, { useMemo } from 'react'

import {
  AdParagraph,
  type CalendarLayoutBlock,
  formatEventTimeRange,
  type NucCalendarEventObjectInterface,
} from 'nucleify'

import './_index.scss'

interface NucCalendarEventBlockProps {
  event: NucCalendarEventObjectInterface
  layout?: CalendarLayoutBlock
  variant?: 'time' | 'month'
  showTime?: boolean
  className?: string
  onSelect?: (event: NucCalendarEventObjectInterface) => void
}

export const NucCalendarEventBlock: React.FC<NucCalendarEventBlockProps> = ({
  event,
  layout,
  variant = 'time',
  showTime = true,
  className,
  onSelect,
}) => {
  const blockStyle = useMemo(() => {
    if (!layout) return undefined
    const color = event.color || undefined
    return {
      top: `${layout.top}%`,
      left: `${layout.left}%`,
      width: `${layout.width}%`,
      height: `${layout.height}%`,
      ...(color ? { borderLeftColor: color } : {}),
    } as React.CSSProperties
  }, [event.color, layout])

  const chipStyle = useMemo(() => {
    const color = event.color || undefined
    return color
      ? ({ borderLeftColor: color } as React.CSSProperties)
      : undefined
  }, [event.color])

  const timeLabel = formatEventTimeRange(event.starts_at, event.ends_at)

  if (variant === 'month') {
    return (
      <button
        type="button"
        className="calendar-month-event-chip"
        style={chipStyle}
        onClick={() => onSelect?.(event)}
      >
        {event.title}
      </button>
    )
  }

  return (
    <button
      type="button"
      className={`calendar-event-block${className ? ` ${className}` : ''}`}
      style={blockStyle}
      data-event-id={String(event.id ?? '')}
      onClick={() => onSelect?.(event)}
    >
      <div className="calendar-event-block-header">
        <AdParagraph
          text={event.title}
          className="calendar-event-block-title"
        />
        {showTime ? (
          <AdParagraph text={timeLabel} className="calendar-event-block-time" />
        ) : null}
      </div>
      <span className="calendar-event-block-resize-handle" />
    </button>
  )
}

// atomic/templates/calendar/event-block/index.vue
<template>
  <button
    v-if="variant === 'month'"
    type="button"
    class="calendar-month-event-chip"
    :style="chipStyle"
    @click="emit('select', event)"
  >
    {{ event.title }}
  </button>
  <button
    v-else
    type="button"
    class="calendar-event-block"
    :data-event-id="String(event.id ?? '')"
    :style="blockStyle"
    @click="emit('select', event)"
  >
    <div class="calendar-event-block-header">
      <p class="calendar-event-block-title">{{ event.title }}</p>
      <p v-if="showTime" class="calendar-event-block-time">{{ timeLabel }}</p>
    </div>
    <span class="calendar-event-block-resize-handle" />
  </button>
</template>

<script setup lang="ts">
import { computed } from 'vue'

import type {
  CalendarLayoutBlock,
  NucCalendarEventObjectInterface,
} from 'nucleify'
import { formatEventTimeRange } from 'nucleify'

const props = withDefaults(
  defineProps<{
    event: NucCalendarEventObjectInterface
    layout?: CalendarLayoutBlock
    variant?: 'time' | 'month'
    showTime?: boolean
  }>(),
  {
    variant: 'time',
    showTime: true,
  }
)

const emit = defineEmits<{
  select: [event: NucCalendarEventObjectInterface]
}>()

const blockStyle = computed(() => {
  if (!props.layout) return {}
  const color = props.event.color || undefined
  return {
    top: `${props.layout.top}%`,
    left: `${props.layout.left}%`,
    width: `${props.layout.width}%`,
    height: `${props.layout.height}%`,
    ...(color ? { borderLeftColor: color } : {}),
  }
})

const chipStyle = computed(() => {
  const color = props.event.color || undefined
  return color ? { borderLeftColor: color } : {}
})

const timeLabel = computed(() =>
  formatEventTimeRange(props.event.starts_at, props.event.ends_at)
)
</script>

<style lang="scss">
@import 'index';
</style>
