// atomic/templates/calendar/board/index.vue
<template>
  <section
    class="calendar-board"
    :class="{ 'calendar-board-loading': loading }"
  >
    <div class="calendar-board-toolbar">
      <div class="calendar-board-toolbar-left">
        <ad-button
          icon="prime:chevron-left"
          ad-type="secondary"
          @click="emit('navigate', -1)"
        />
        <ad-button label="Today" ad-type="secondary" @click="emit('today')" />
        <ad-button
          icon="prime:chevron-right"
          ad-type="secondary"
          @click="emit('navigate', 1)"
        />
        <p class="calendar-board-range-label">{{ rangeLabel }}</p>
      </div>
      <div class="calendar-board-toolbar-right">
        <div class="calendar-board-view-switch">
          <button
            v-for="item in views"
            :key="item"
            type="button"
            class="calendar-board-view-button"
            :class="{
              'calendar-board-view-button-active': item === view,
            }"
            @click="emit('view-change', item)"
          >
            {{ viewLabels[item] }}
          </button>
        </div>
        <ad-button
          icon="prime:cog"
          ad-type="secondary"
          aria-label="Integrations"
          :class="{ 'calendar-board-integrations-active': integrationsOpen }"
          @click="emit('open-integrations')"
        />
        <ad-button
          label="New event"
          icon="prime:plus"
          ad-type="main"
          @click="emit('new-event')"
        />
      </div>
    </div>
    <div class="calendar-board-content">
      <nuc-calendar-month-grid
        v-if="view === 'month'"
        :anchor="anchor"
        :events="events"
        :week-starts-on="weekStartsOn"
        @day-click="emit('day-click', $event)"
        @event-select="emit('event-select', $event)"
      />
      <nuc-calendar-week-grid
        v-else-if="view === 'week'"
        :anchor="anchor"
        :events="events"
        :day-start-hour="dayStartHour"
        :day-end-hour="dayEndHour"
        :week-starts-on="weekStartsOn"
        @slot-click="(day, hour) => emit('slot-click', day, hour)"
        @event-select="emit('event-select', $event)"
      />
      <nuc-calendar-day-grid
        v-else
        :day="anchor"
        :events="events"
        :day-start-hour="dayStartHour"
        :day-end-hour="dayEndHour"
        @slot-click="(day, hour) => emit('slot-click', day, hour)"
        @event-select="emit('event-select', $event)"
      />
    </div>
  </section>
</template>

<script setup lang="ts">
import { computed } from 'vue'

import type { CalendarView, NucCalendarEventObjectInterface } from 'nucleify'
import { CALENDAR_VIEWS, formatRangeLabel } from 'nucleify'

const props = defineProps<{
  view: CalendarView
  anchor: Date
  events: NucCalendarEventObjectInterface[]
  loading?: boolean
  dayStartHour: number
  dayEndHour: number
  weekStartsOn?: number
  integrationsOpen?: boolean
}>()

const emit = defineEmits<{
  'view-change': [view: CalendarView]
  navigate: [direction: -1 | 1]
  today: []
  'new-event': []
  'open-integrations': []
  'slot-click': [day: Date, hour: number]
  'day-click': [day: Date]
  'event-select': [event: NucCalendarEventObjectInterface]
}>()

const views = CALENDAR_VIEWS

const viewLabels: Record<CalendarView, string> = {
  day: 'Day',
  week: 'Week',
  month: 'Month',
}

const rangeLabel = computed(() =>
  formatRangeLabel(props.view, props.anchor, props.weekStartsOn ?? 1)
)
</script>

<style lang="scss">
@import 'index';
</style>

// atomic/templates/calendar/board/index.tsx
'use client'

import React, { useMemo } from 'react'

import {
  AdButton,
  AdParagraph,
  CALENDAR_VIEWS,
  type CalendarView,
  formatRangeLabel,
  NucCalendarDayGrid,
  type NucCalendarEventObjectInterface,
  NucCalendarMonthGrid,
  NucCalendarWeekGrid,
  t,
} from 'nucleify'

import './_index.scss'

interface NucCalendarBoardProps {
  view: CalendarView
  anchor: Date
  events: NucCalendarEventObjectInterface[]
  loading?: boolean
  dayStartHour: number
  dayEndHour: number
  weekStartsOn?: number
  integrationsOpen?: boolean
  onViewChange?: (view: CalendarView) => void
  onNavigate?: (direction: -1 | 1) => void
  onToday?: () => void
  onNewEvent?: () => void
  onOpenIntegrations?: () => void
  onSlotClick?: (day: Date, hour: number) => void
  onDayClick?: (day: Date) => void
  onEventSelect?: (event: NucCalendarEventObjectInterface) => void
}

export const NucCalendarBoard: React.FC<NucCalendarBoardProps> = ({
  view,
  anchor,
  events,
  loading = false,
  dayStartHour,
  dayEndHour,
  weekStartsOn = 1,
  integrationsOpen = false,
  onViewChange,
  onNavigate,
  onToday,
  onNewEvent,
  onOpenIntegrations,
  onSlotClick,
  onDayClick,
  onEventSelect,
}) => {
  const rangeLabel = useMemo(
    () => formatRangeLabel(view, anchor, weekStartsOn),
    [anchor, view, weekStartsOn]
  )

  const viewLabels = useMemo<Record<CalendarView, string>>(
    () => ({
      day: t('calendar-view-day'),
      week: t('calendar-view-week'),
      month: t('calendar-view-month'),
    }),
    []
  )

  return (
    <section
      className={`calendar-board${loading ? ' calendar-board-loading' : ''}`}
    >
      <div className="calendar-board-toolbar">
        <div className="calendar-board-toolbar-left">
          <AdButton
            icon="prime:chevron-left"
            nuiType="secondary"
            onClick={() => onNavigate?.(-1)}
          />
          <AdButton
            label={t('calendar-today')}
            nuiType="secondary"
            onClick={onToday}
          />
          <AdButton
            icon="prime:chevron-right"
            nuiType="secondary"
            onClick={() => onNavigate?.(1)}
          />
          <AdParagraph
            text={rangeLabel}
            className="calendar-board-range-label"
          />
        </div>
        <div className="calendar-board-toolbar-right">
          <div className="calendar-board-view-switch">
            {CALENDAR_VIEWS.map((item) => (
              <button
                key={item}
                type="button"
                className={`calendar-board-view-button${item === view ? ' calendar-board-view-button-active' : ''}`}
                onClick={() => onViewChange?.(item)}
              >
                {viewLabels[item]}
              </button>
            ))}
          </div>
          <AdButton
            icon="prime:cog"
            nuiType="secondary"
            aria-label={t('calendar-integrations')}
            className={
              integrationsOpen ? 'calendar-board-integrations-active' : ''
            }
            onClick={onOpenIntegrations}
          />
          <AdButton
            label={t('calendar-new-event')}
            icon="prime:plus"
            nuiType="main"
            onClick={onNewEvent}
          />
        </div>
      </div>
      <div className="calendar-board-content">
        {view === 'month' ? (
          <NucCalendarMonthGrid
            anchor={anchor}
            events={events}
            weekStartsOn={weekStartsOn}
            onDayClick={onDayClick}
            onEventSelect={onEventSelect}
          />
        ) : view === 'week' ? (
          <NucCalendarWeekGrid
            anchor={anchor}
            events={events}
            dayStartHour={dayStartHour}
            dayEndHour={dayEndHour}
            weekStartsOn={weekStartsOn}
            onSlotClick={onSlotClick}
            onEventSelect={onEventSelect}
          />
        ) : (
          <NucCalendarDayGrid
            day={anchor}
            events={events}
            dayStartHour={dayStartHour}
            dayEndHour={dayEndHour}
            onSlotClick={onSlotClick}
            onEventSelect={onEventSelect}
          />
        )}
      </div>
    </section>
  )
}
