// atomic/templates/calendar/week-grid/index.vue
<template>
  <div class="calendar-week-grid">
    <div class="calendar-week-grid-header">
      <div class="calendar-week-grid-header-spacer" />
      <div
        v-for="day in days"
        :key="day.toISOString()"
        class="calendar-week-grid-day-header"
      >
        <p class="calendar-week-grid-weekday">{{ formatWeekdayLabel(day) }}</p>
        <p
          class="calendar-week-grid-day-number"
          :class="{
            'calendar-week-grid-day-number-today': isToday(day),
          }"
        >
          {{ formatDayNumber(day) }}
        </p>
      </div>
    </div>
    <div ref="bodyRef" class="calendar-week-grid-body">
      <nuc-calendar-day-grid
        :day="days[0] ?? anchor"
        :events="[]"
        :day-start-hour="dayStartHour"
        :day-end-hour="dayEndHour"
        :show-hours="true"
        :scrollable="false"
        class="calendar-week-grid-hours-column"
        @slot-click="() => undefined"
      />
      <div
        v-for="day in days"
        :key="`col-${day.toISOString()}`"
        class="calendar-week-grid-day-column"
      >
        <nuc-calendar-day-grid
          :day="day"
          :events="events"
          :day-start-hour="dayStartHour"
          :day-end-hour="dayEndHour"
          :show-hours="false"
          :scrollable="false"
          @slot-click="(slotDay, hour) => emit('slot-click', slotDay, hour)"
          @event-select="emit('event-select', $event)"
        />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, nextTick, onMounted, ref, watch } from 'vue'

import type { NucCalendarEventObjectInterface } from 'nucleify'
import {
  calendarScrollTopForNow,
  CALENDAR_HOUR_HEIGHT,
  formatDayNumber,
  formatWeekdayLabel,
  isToday,
  weekDays,
} from 'nucleify'

const props = defineProps<{
  anchor: Date
  events: NucCalendarEventObjectInterface[]
  dayStartHour: number
  dayEndHour: number
  weekStartsOn?: number
}>()

const emit = defineEmits<{
  'slot-click': [day: Date, hour: number]
  'event-select': [event: NucCalendarEventObjectInterface]
}>()

const bodyRef = ref<HTMLElement | null>(null)

const days = computed(() => weekDays(props.anchor, props.weekStartsOn ?? 1))

const showsToday = computed(() => days.value.some((day) => isToday(day)))

function scrollToNow(): void {
  if (!showsToday.value) return
  const scrollEl = bodyRef.value
  if (!scrollEl) return
  scrollEl.scrollTop = calendarScrollTopForNow(
    scrollEl,
    props.dayStartHour,
    props.dayEndHour,
    CALENDAR_HOUR_HEIGHT
  )
}

onMounted(() => {
  void nextTick(scrollToNow)
})

watch(
  () => props.anchor.toDateString(),
  () => {
    void nextTick(scrollToNow)
  }
)
</script>

<style lang="scss">
@import 'index';
</style>

// atomic/templates/calendar/week-grid/index.tsx
'use client'

import React, { useEffect, useMemo, useRef } from 'react'

import {
  CALENDAR_HOUR_HEIGHT,
  calendarScrollTopForNow,
  formatDayNumber,
  formatWeekdayLabel,
  isToday,
  NucCalendarDayGrid,
  type NucCalendarEventObjectInterface,
  weekDays,
} from 'nucleify'

import './_index.scss'

interface NucCalendarWeekGridProps {
  anchor: Date
  events: NucCalendarEventObjectInterface[]
  dayStartHour: number
  dayEndHour: number
  weekStartsOn?: number
  onSlotClick?: (day: Date, hour: number) => void
  onEventSelect?: (event: NucCalendarEventObjectInterface) => void
}

export const NucCalendarWeekGrid: React.FC<NucCalendarWeekGridProps> = ({
  anchor,
  events,
  dayStartHour,
  dayEndHour,
  weekStartsOn = 1,
  onSlotClick,
  onEventSelect,
}) => {
  const bodyRef = useRef<HTMLDivElement>(null)

  const days = useMemo(
    () => weekDays(anchor, weekStartsOn),
    [anchor, weekStartsOn]
  )

  const showsToday = useMemo(() => days.some((day) => isToday(day)), [days])

  useEffect(() => {
    if (!showsToday) return
    const scrollEl = bodyRef.current
    if (!scrollEl) return
    scrollEl.scrollTop = calendarScrollTopForNow(
      scrollEl,
      dayStartHour,
      dayEndHour,
      CALENDAR_HOUR_HEIGHT
    )
  }, [anchor, dayEndHour, dayStartHour, showsToday])

  return (
    <div className="calendar-week-grid">
      <div className="calendar-week-grid-header">
        <div className="calendar-week-grid-header-spacer" />
        {days.map((day) => (
          <div
            key={day.toISOString()}
            className="calendar-week-grid-day-header"
          >
            <p className="calendar-week-grid-weekday">
              {formatWeekdayLabel(day)}
            </p>
            <p
              className={`calendar-week-grid-day-number${isToday(day) ? ' calendar-week-grid-day-number-today' : ''}`}
            >
              {formatDayNumber(day)}
            </p>
          </div>
        ))}
      </div>
      <div ref={bodyRef} className="calendar-week-grid-body">
        <div className="calendar-week-grid-hours-column">
          <NucCalendarDayGrid
            day={days[0] ?? anchor}
            events={[]}
            dayStartHour={dayStartHour}
            dayEndHour={dayEndHour}
            showHours
            scrollable={false}
          />
        </div>
        {days.map((day) => (
          <div
            key={`col-${day.toISOString()}`}
            className="calendar-week-grid-day-column"
          >
            <NucCalendarDayGrid
              day={day}
              events={events}
              dayStartHour={dayStartHour}
              dayEndHour={dayEndHour}
              showHours={false}
              scrollable={false}
              onSlotClick={onSlotClick}
              onEventSelect={onEventSelect}
            />
          </div>
        ))}
      </div>
    </div>
  )
}
