// atomic/pages/index.vue
<template>
  <div class="panel-container">
    <nuc-calendar-board
      :view="view"
      :anchor="anchor"
      :events="eventsList"
      :loading="loading"
      :day-start-hour="dayStartHour"
      :day-end-hour="dayEndHour"
      :week-starts-on="weekStartsOn"
      :integrations-open="integrationsVisible"
      @view-change="setView"
      @navigate="navigate"
      @today="goToday"
      @new-event="openCreateDialog"
      @open-integrations="integrationsVisible = true"
      @slot-click="openCreateFromSlot"
      @day-click="openDayView"
      @event-select="openEditDialog"
      @event-move="moveEvent"
      @event-resize="moveEvent"
    />
    <ad-dialog
      :visible="integrationsVisible"
      modal
      class="calendar-integrations-dialog"
      @update:visible="onIntegrationsVisibleUpdate"
    >
      <template #header>
        <span>{{ t('calendar-integrations') }}</span>
      </template>
      <nuc-calendar-integration-grid :integrations="integrationsList" />
    </ad-dialog>
    <nuc-calendar-event-dialog
      :visible="dialogVisible"
      :draft="eventDraft"
      :mode="dialogMode"
      @close="closeDialog"
      @save="saveEvent"
      @cancel-event="removeEvent"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'

import type {
  CalendarEventDraft,
  CalendarView,
  NucCalendarEventObjectInterface,
} from 'nucleify'
import {
  buildEventDraftFromSlot,
  calendarRequests,
  CALENDAR_DAY_END_HOUR,
  CALENDAR_DAY_START_HOUR,
  CALENDAR_DEFAULT_VIEW,
  CALENDAR_SLOT_DURATION_MINUTES,
  CALENDAR_WEEK_STARTS_ON,
  defaultNewEventHour,
  flashToast,
  getRangeForView,
  parseCalendarView,
  shiftCalendarAnchor,
  toIsoRange,
} from 'nucleify'

const {
  events,
  integrations,
  loading,
  getIntegrations,
  getEventsInRange,
  createEvent,
  moveEventTimes,
  updateEvent,
  cancelEvent,
} = calendarRequests()

const { t } = useI18n()

const view = ref<CalendarView>(parseCalendarView(CALENDAR_DEFAULT_VIEW))
const anchor = ref(new Date())
const integrationsVisible = ref(false)
const dialogVisible = ref(false)
const dialogMode = ref<'create' | 'edit'>('create')
const eventDraft = ref<CalendarEventDraft>(
  buildEventDraftFromSlot(new Date(), 9)
)

const dayStartHour = CALENDAR_DAY_START_HOUR
const dayEndHour = CALENDAR_DAY_END_HOUR
const weekStartsOn = CALENDAR_WEEK_STARTS_ON

const eventsList = computed(
  () => (events.value ?? []) as NucCalendarEventObjectInterface[]
)
const integrationsList = computed(() => integrations.value ?? [])

async function refreshEvents(): Promise<void> {
  const range = getRangeForView(view.value, anchor.value, weekStartsOn)
  const iso = toIsoRange(range.from, range.to)
  await getEventsInRange(iso.from, iso.to, false)
}

function onIntegrationsVisibleUpdate(value: boolean): void {
  integrationsVisible.value = value
}

function setView(next: CalendarView): void {
  view.value = next
}

function navigate(direction: -1 | 1): void {
  anchor.value = shiftCalendarAnchor(view.value, anchor.value, direction)
}

function goToday(): void {
  anchor.value = new Date()
}

function openCreateDialog(): void {
  dialogMode.value = 'create'
  eventDraft.value = buildEventDraftFromSlot(
    anchor.value,
    defaultNewEventHour(dayStartHour, dayEndHour),
    CALENDAR_SLOT_DURATION_MINUTES
  )
  dialogVisible.value = true
}

function openCreateFromSlot(day: Date, hour: number): void {
  dialogMode.value = 'create'
  eventDraft.value = buildEventDraftFromSlot(
    day,
    hour,
    CALENDAR_SLOT_DURATION_MINUTES
  )
  dialogVisible.value = true
}

function openDayView(day: Date): void {
  view.value = 'day'
  anchor.value = day
}

function openEditDialog(event: NucCalendarEventObjectInterface): void {
  dialogMode.value = 'edit'
  eventDraft.value = { ...event }
  dialogVisible.value = true
}

function closeDialog(): void {
  dialogVisible.value = false
}

async function saveEvent(draft: CalendarEventDraft): Promise<void> {
  const ok =
    dialogMode.value === 'edit' && draft.id
      ? await updateEvent(draft.id, draft)
      : await createEvent(draft)
  if (!ok) return
  dialogVisible.value = false
  await refreshEvents()
}

async function removeEvent(id: number): Promise<void> {
  const ok = await cancelEvent(id)
  if (!ok) return
  dialogVisible.value = false
  await refreshEvents()
}

async function moveEvent(payload: {
  id: number
  starts_at: string
  ends_at: string
}): Promise<void> {
  const ok = await moveEventTimes(
    payload.id,
    payload.starts_at,
    payload.ends_at
  )
  if (!ok) return
  flashToast(t('toast-calendar-event-updated'), 'success', 2000)
  await refreshEvents()
}

onMounted(async () => {
  await Promise.all([getIntegrations(false), refreshEvents()])
})

watch([view, anchor], () => {
  void refreshEvents()
})
</script>

<style lang="scss">
@import 'index';
</style>

// atomic/pages/index.tsx
'use client'

import type { JSX } from 'react'
import { useEffect, useState } from 'react'

import {
  AdDialog,
  buildEventDraftFromSlot,
  CALENDAR_DAY_END_HOUR,
  CALENDAR_DAY_START_HOUR,
  CALENDAR_DEFAULT_VIEW,
  CALENDAR_SLOT_DURATION_MINUTES,
  CALENDAR_WEEK_STARTS_ON,
  type CalendarEventDraft,
  type CalendarView,
  calendarRequests,
  defaultNewEventHour,
  flashToast,
  getRangeForView,
  NucCalendarBoard,
  NucCalendarEventDialog,
  type NucCalendarEventObjectInterface,
  NucCalendarIntegrationGrid,
  parseCalendarView,
  shiftCalendarAnchor,
  t,
  toIsoRange,
} from 'nucleify'

import './_index.scss'

export function NucCalendarPage(): JSX.Element {
  const {
    events,
    integrations,
    loading,
    getIntegrations,
    getEventsInRange,
    createEvent,
    moveEventTimes,
    updateEvent,
    cancelEvent,
  } = calendarRequests('next')

  const [view, setView] = useState<CalendarView>(
    parseCalendarView(CALENDAR_DEFAULT_VIEW)
  )
  const [anchor, setAnchor] = useState(() => new Date())
  const [integrationsVisible, setIntegrationsVisible] = useState(false)
  const [dialogVisible, setDialogVisible] = useState(false)
  const [dialogMode, setDialogMode] = useState<'create' | 'edit'>('create')
  const [eventDraft, setEventDraft] = useState<CalendarEventDraft>(
    buildEventDraftFromSlot(new Date(), CALENDAR_DAY_START_HOUR)
  )

  const eventsList = (events ?? []) as NucCalendarEventObjectInterface[]
  const integrationsList = integrations ?? []

  async function refreshEvents(): Promise<void> {
    const range = getRangeForView(view, anchor, CALENDAR_WEEK_STARTS_ON)
    const iso = toIsoRange(range.from, range.to)
    await getEventsInRange(iso.from, iso.to, false)
  }

  const navigate = (direction: -1 | 1) => {
    setAnchor((current) => shiftCalendarAnchor(view, current, direction))
  }

  const goToday = () => {
    setAnchor(new Date())
  }

  const openCreateDialog = () => {
    setDialogMode('create')
    setEventDraft(
      buildEventDraftFromSlot(
        anchor,
        defaultNewEventHour(CALENDAR_DAY_START_HOUR, CALENDAR_DAY_END_HOUR),
        CALENDAR_SLOT_DURATION_MINUTES
      )
    )
    setDialogVisible(true)
  }

  const openCreateFromSlot = (day: Date, hour: number) => {
    setDialogMode('create')
    setEventDraft(
      buildEventDraftFromSlot(day, hour, CALENDAR_SLOT_DURATION_MINUTES)
    )
    setDialogVisible(true)
  }

  const openDayView = (day: Date) => {
    setView('day')
    setAnchor(day)
  }

  const openEditDialog = (event: NucCalendarEventObjectInterface) => {
    setDialogMode('edit')
    setEventDraft({ ...event })
    setDialogVisible(true)
  }

  const saveEvent = async (draft: CalendarEventDraft) => {
    const ok =
      dialogMode === 'edit' && draft.id
        ? await updateEvent(draft.id, draft)
        : await createEvent(draft)
    if (!ok) return
    setDialogVisible(false)
    await refreshEvents()
  }

  const removeEvent = async (id: number) => {
    const ok = await cancelEvent(id)
    if (!ok) return
    setDialogVisible(false)
    await refreshEvents()
  }

  const moveEvent = async (payload: {
    id: number
    starts_at: string
    ends_at: string
  }) => {
    const ok = await moveEventTimes(
      payload.id,
      payload.starts_at,
      payload.ends_at
    )
    if (!ok) return
    flashToast(t('toast-calendar-event-updated'), 'success', 2000)
    await refreshEvents()
  }

  useEffect(() => {
    void getIntegrations(false)
  }, [])

  useEffect(() => {
    const range = getRangeForView(view, anchor, CALENDAR_WEEK_STARTS_ON)
    const iso = toIsoRange(range.from, range.to)
    void getEventsInRange(iso.from, iso.to, false)
  }, [view, anchor])

  return (
    <div className="panel-container">
      <NucCalendarBoard
        view={view}
        anchor={anchor}
        events={eventsList}
        loading={loading}
        dayStartHour={CALENDAR_DAY_START_HOUR}
        dayEndHour={CALENDAR_DAY_END_HOUR}
        weekStartsOn={CALENDAR_WEEK_STARTS_ON}
        integrationsOpen={integrationsVisible}
        onViewChange={setView}
        onNavigate={navigate}
        onToday={goToday}
        onNewEvent={openCreateDialog}
        onOpenIntegrations={() => setIntegrationsVisible(true)}
        onSlotClick={openCreateFromSlot}
        onDayClick={openDayView}
        onEventSelect={openEditDialog}
        onEventMove={moveEvent}
        onEventResize={moveEvent}
      />
      <AdDialog
        visible={integrationsVisible}
        modal
        className="calendar-integrations-dialog"
        showHeader
        header={<span>{t('calendar-integrations')}</span>}
        onHide={() => setIntegrationsVisible(false)}
      >
        <NucCalendarIntegrationGrid integrations={integrationsList} />
      </AdDialog>
      <NucCalendarEventDialog
        visible={dialogVisible}
        draft={eventDraft}
        mode={dialogMode}
        onClose={() => setDialogVisible(false)}
        onSave={saveEvent}
        onCancelEvent={removeEvent}
      />
    </div>
  )
}
