// atomic/templates/calendar/integration-grid/index.vue
<template>
  <section class="calendar-integration-grid">
    <header class="calendar-integration-grid-header">
      <h2 class="calendar-integration-grid-title">Connect your calendars</h2>
      <p class="calendar-integration-grid-subtitle">
        Import meetings from Calendly, Google Calendar, Outlook, and more in one
        place.
      </p>
    </header>
    <div class="calendar-integration-grid-items">
      <nuc-calendar-integration-tile
        v-for="integration in integrations"
        :key="integration.id"
        :integration="integration"
        @connect="emit('connect', $event)"
      />
    </div>
  </section>
</template>

<script setup lang="ts">
import type { CalendarIntegrationStatusInterface } from 'nucleify'

defineProps<{
  integrations: CalendarIntegrationStatusInterface[]
}>()

const emit = defineEmits<{
  connect: [providerId: CalendarIntegrationStatusInterface['id']]
}>()
</script>

<style lang="scss">
@import 'index';
</style>

// atomic/templates/calendar/integration-grid/index.tsx
'use client'

import React from 'react'

import {
  AdParagraph,
  type CalendarIntegrationStatusInterface,
  NucCalendarIntegrationTile,
} from 'nucleify'

import './_index.scss'

interface NucCalendarIntegrationGridProps {
  integrations: CalendarIntegrationStatusInterface[]
  onConnect?: (providerId: CalendarIntegrationStatusInterface['id']) => void
}

export const NucCalendarIntegrationGrid: React.FC<
  NucCalendarIntegrationGridProps
> = ({ integrations, onConnect }) => {
  return (
    <section className="calendar-integration-grid">
      <header className="calendar-integration-grid-header">
        <h2 className="calendar-integration-grid-title">
          Connect your calendars
        </h2>
        <AdParagraph
          text="Import meetings from Calendly, Google Calendar, Outlook, and more in one place."
          className="calendar-integration-grid-subtitle"
        />
      </header>
      <div className="calendar-integration-grid-items">
        {integrations.map((integration) => (
          <NucCalendarIntegrationTile
            key={integration.id}
            integration={integration}
            onConnect={onConnect}
          />
        ))}
      </div>
    </section>
  )
}
