// atomic/templates/calendar/month-grid/index.tsx
'use client'

import React, { useMemo } from 'react'

import {
  eventsForDay,
  formatDayNumber,
  formatWeekdayLabel,
  isSameMonth,
  isToday,
  monthDayEventLimit,
  monthGridDays,
  NucCalendarEventBlock,
  type NucCalendarEventObjectInterface,
  weekDays,
} from 'nucleify'

import './_index.scss'

interface NucCalendarMonthGridProps {
  anchor: Date
  events: NucCalendarEventObjectInterface[]
  weekStartsOn?: number
  onDayClick?: (day: Date) => void
  onEventSelect?: (event: NucCalendarEventObjectInterface) => void
}

export const NucCalendarMonthGrid: React.FC<NucCalendarMonthGridProps> = ({
  anchor,
  events,
  weekStartsOn = 1,
  onDayClick,
  onEventSelect,
}) => {
  const days = useMemo(
    () => monthGridDays(anchor, weekStartsOn),
    [anchor, weekStartsOn]
  )

  const weekdayLabels = useMemo(() => {
    const start = weekDays(anchor, weekStartsOn)[0] ?? anchor
    return weekDays(start, weekStartsOn).map((day) =>
      formatWeekdayLabel(day, 'en', 'short')
    )
  }, [anchor, weekStartsOn])

  const monthEvents = (day: Date) =>
    monthDayEventLimit(eventsForDay(events, day))

  return (
    <div className="calendar-month-grid">
      <div className="calendar-month-grid-weekdays">
        {weekdayLabels.map((weekday) => (
          <div key={weekday} className="calendar-month-grid-weekday">
            {weekday}
          </div>
        ))}
      </div>
      <div className="calendar-month-grid-cells">
        {days.map((day) => {
          const { visible, hiddenCount } = monthEvents(day)
          return (
            <div
              key={day.toISOString()}
              className={`calendar-month-grid-cell${!isSameMonth(day, anchor) ? ' calendar-month-grid-cell-outside' : ''}${isToday(day) ? ' calendar-month-grid-cell-today' : ''}`}
              onClick={() => onDayClick?.(day)}
            >
              <p className="calendar-month-grid-day-number">
                {formatDayNumber(day)}
              </p>
              {visible.map((event) => (
                <NucCalendarEventBlock
                  key={event.id}
                  variant="month"
                  event={event}
                  showTime={false}
                  onSelect={onEventSelect}
                />
              ))}
              {hiddenCount > 0 ? (
                <p className="calendar-month-grid-more">+{hiddenCount} more</p>
              ) : null}
            </div>
          )
        })}
      </div>
    </div>
  )
}

// atomic/templates/calendar/month-grid/index.vue
<template>
  <div class="calendar-month-grid">
    <div class="calendar-month-grid-weekdays">
      <div
        v-for="weekday in weekdayLabels"
        :key="weekday"
        class="calendar-month-grid-weekday"
      >
        {{ weekday }}
      </div>
    </div>
    <div class="calendar-month-grid-cells">
      <div
        v-for="day in days"
        :key="day.toISOString()"
        class="calendar-month-grid-cell"
        :class="{
          'calendar-month-grid-cell-outside': !isSameMonth(day, anchor),
          'calendar-month-grid-cell-today': isToday(day),
        }"
        @click="emit('day-click', day)"
      >
        <p class="calendar-month-grid-day-number">{{ formatDayNumber(day) }}</p>
        <nuc-calendar-event-block
          v-for="event in monthEvents(day).visible"
          :key="event.id"
          variant="month"
          :event="event"
          :show-time="false"
          @select="emit('event-select', $event)"
        />
        <p
          v-if="monthEvents(day).hiddenCount > 0"
          class="calendar-month-grid-more"
        >
          +{{ monthEvents(day).hiddenCount }}
          more
        </p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'

import type { NucCalendarEventObjectInterface } from 'nucleify'
import {
  eventsForDay,
  formatDayNumber,
  formatWeekdayLabel,
  isSameMonth,
  isToday,
  monthDayEventLimit,
  monthGridDays,
  weekDays,
} from 'nucleify'

const props = defineProps<{
  anchor: Date
  events: NucCalendarEventObjectInterface[]
  weekStartsOn?: number
}>()

const emit = defineEmits<{
  'day-click': [day: Date]
  'event-select': [event: NucCalendarEventObjectInterface]
}>()

const days = computed(() =>
  monthGridDays(props.anchor, props.weekStartsOn ?? 1)
)

const weekdayLabels = computed(() => {
  const start =
    weekDays(props.anchor, props.weekStartsOn ?? 1)[0] ?? props.anchor
  return weekDays(start, props.weekStartsOn ?? 1).map((day) =>
    formatWeekdayLabel(day, 'en', 'short')
  )
})

function monthEvents(day: Date) {
  return monthDayEventLimit(eventsForDay(props.events, day))
}
</script>

<style lang="scss">
@import 'index';
</style>
