// atomic/templates/calendar/integration-tile/index.tsx
'use client'

import React from 'react'

import {
  AdButton,
  AdIcon,
  AdParagraph,
  CALENDAR_INTEGRATION_ICONS,
  type CalendarIntegrationStatusInterface,
  t,
} from 'nucleify'

import './_index.scss'

interface NucCalendarIntegrationTileProps {
  integration: CalendarIntegrationStatusInterface
  onConnect?: (providerId: CalendarIntegrationStatusInterface['id']) => void
}

export const NucCalendarIntegrationTile: React.FC<
  NucCalendarIntegrationTileProps
> = ({ integration, onConnect }) => {
  const icon = CALENDAR_INTEGRATION_ICONS[integration.id] ?? 'mdi:calendar'
  const connectLabel = integration.connectable
    ? t('calendar-connect')
    : t('common-coming-soon')

  return (
    <article className="calendar-integration-tile">
      <div className="calendar-integration-tile-header">
        <div className="calendar-integration-tile-icon">
          <AdIcon icon={icon} size="1.5em" />
        </div>
        <AdParagraph
          text={integration.name}
          className="calendar-integration-tile-name"
        />
      </div>
      <AdParagraph
        text={integration.description}
        className="calendar-integration-tile-description"
      />
      <div className="calendar-integration-tile-footer">
        {integration.connected ? (
          <span className="calendar-integration-tile-badge">
            {t('calendar-connected')}
          </span>
        ) : null}
        <AdButton
          label={integration.connected ? t('calendar-manage') : connectLabel}
          nuiType={integration.connected ? 'secondary' : 'main'}
          disabled={!integration.connectable}
          onClick={() => onConnect?.(integration.id)}
        />
      </div>
    </article>
  )
}

// atomic/templates/calendar/integration-tile/index.vue
<template>
  <article class="calendar-integration-tile">
    <div class="calendar-integration-tile-header">
      <div class="calendar-integration-tile-icon">
        <ad-icon :icon="icon" size="1.5em" />
      </div>
      <p class="calendar-integration-tile-name">{{ integration.name }}</p>
    </div>
    <p class="calendar-integration-tile-description">
      {{ integration.description }}
    </p>
    <div class="calendar-integration-tile-footer">
      <span
        v-if="integration.connected"
        class="calendar-integration-tile-badge"
      >
        {{ t('calendar-connected') }}
      </span>
      <ad-button
        :label="
          integration.connected
            ? t('calendar-manage')
            : connectLabel
        "
        :nui-type="integration.connected ? 'secondary' : 'main'"
        :disabled="!integration.connectable"
        @click="emit('connect', integration.id)"
      />
    </div>
  </article>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'

import type { CalendarIntegrationStatusInterface } from 'nucleify'
import { CALENDAR_INTEGRATION_ICONS } from 'nucleify'

const props = defineProps<{
  integration: CalendarIntegrationStatusInterface
}>()

const emit = defineEmits<{
  connect: [providerId: CalendarIntegrationStatusInterface['id']]
}>()

const { t } = useI18n()

const icon = computed(
  () => CALENDAR_INTEGRATION_ICONS[props.integration.id] ?? 'mdi:calendar'
)

const connectLabel = computed(() =>
  props.integration.connectable
    ? t('calendar-connect')
    : t('common-coming-soon')
)
</script>

<style lang="scss">
@import 'index';
</style>
